She scratches a letter
Into a wall made of stone
Maybe someday another child
Won't feel as alone as she does
It's been two years and counting
Since they put her in this place
She's been diagnosed
By some stupid fuck
And mommy agrees, yeah

Why go home?
Why go home?
Why go home?

She seems to be stronger
But what they want her to be is weak
She could play pretend
She could join the game, boy
She could be another clone
Ooh, ow
Ah, yeah

Why go home?
Why go home?
Why go home?
Why go home?
What you taught me (why go home?)
Put me here (why go home?)
Don't come visit (why go home?)
Mother, sing it

Oh, why go home?
Why go home?
Why go home?
Why go home?
What you taught me (why go home?)
Put me here (why go home?)
Don't come visit (why go home?)
Mother, Mother, yeah (why go home?)

Why go home?
Why go home?
Why go home?
Why go home?
Why go home?
Why go home?
Why?